fix: use standard error

diff --git a/bin/make-gitattributes b/bin/make-gitattributes
--- a/bin/make-gitattributes
+++ b/bin/make-gitattributes
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [[ -e .gitattributes ]]; then
-  printf '\033[31merror:\033[m `.gitattributes` alreadly exists\n'
+  printf '\033[31merror:\033[m `.gitattributes` alreadly exists\n' 1>&2
   exit 1
 fi
 
